package api

import "time"

type Site struct {
	id        int
	name      string
	accountId int

	// { Active | Pending Communication }
	status string

	peakPower float32

	// { EUR }
	currency string

	// Precision: 2006-01-02 15:04:05
	installationDate time.Time

	// Precision: 2006-01-02
	ptoDate time.Time

	notes string

	// { Optimizers and inverters | Safety and monitoring interface | Monitoring combiner boxes }
	siteType string

	location Location

	//  only available when using an API_KEY generated by an account. API_KEY generated at the site level does not return this information
	alertQuantity int

	//  only available when using an API_KEY generated by an account. API_KEY generated at the site level does not return this information
	// { NONE }
	alertSeverity string

	uris Uris

	publicSettings PublicSettings
}
